package com.geng.gameengine.login;

/**
 * Created by lifangkai on 15/9/6.
 */
public enum COKLoginExceptionType {
    CURRENT,
    ACCOUNT_NOT_EXIST,
    ACCOUNT_EXIST_PF_ID,
    ACCOUNT_EXIST_DEVICE,
    MOVED,
    BAN_TIME,
    PF_ID_BLANK,
    UID_PF_ID_NOT_MAPPING,
    SECURITY_CODE_NO,
    SECURITY_CODE_ERROR,
    SECURITY_CODE_CURRENT_TIME,
    AVG,
    WEB_STEAL_ACCOUNT,
    MOBILE_STEAL_ACCOUNT,
    CENTER_SERVER_REGISTER,
    BATCH_REGISTER_COUNT_PER_MAC_ADDRESS,
    BATCH_REGISTER_NOT_CALL_SERVER_LIST,
    PACKAGE_NAME,
    TEST_SERVER_COUNT_DAILY,
    DATA_LOAD,
    JOIN_ZONE,
    BAN_IP,
    BAN_DEVICE,
    ROBBER,
    BAN_CHECK,
    BAN_PASSWD,
}
