package com.geng.exceptions;

/**
 * Created by lifangkai on 15/5/11.
 */
public enum ExceptionMonitorType {
    OTHER, LOGIN, STARTUP, REGISTER, CMD, PUSH, PAY,
    LOCAL_DB, GLOBAL_DB, CROSS_DB, LOCAL_REDIS, GLOBAL_REDIS, CHAT_ROOM,
    SCHEDULE, WORLD, ACTIVATION_CODE, PARSE, SERVER_MAIL, NAME_LENGTH, TERRITORY, CROSS_KINGDOM_FIGHT, FAULT,
    FIGHT_FOR_KING, RETURN_HOME, GEOIP, MARCH_KEY, SOLDIER, SOCIAL, DRAGON_BATTLE, SKILL, REDIS, CROSS_SERVER, CHEAT, HERO_ACTIVITY,
    FARMER,SUPERSTRONGHOLD,ALLIANCE_PAY_TOTAL,FIGHTING, CROSS_THRONE_FIGHT, CROSS_SERVER_SOLDIER,ALLIANCE, SERVER_PUSH
}